"""Tests for sql_to_dag.generator — end-to-end DAG compilation."""

import re
import pytest

from sql_to_dag.generator import compile_sql_string, compile_sql_file


# ---------------------------------------------------------------------------
# Fixtures / constants
# ---------------------------------------------------------------------------

SAMPLE_SQL = """
CREATE TABLE staging.customer_txn AS
SELECT customer_id, SUM(amount) as total_amount, COUNT(*) as txn_count
FROM raw.transactions
WHERE txn_date >= TRUNC(SYSDATE) - 30
GROUP BY customer_id;

CREATE TABLE mart.customer_summary AS
SELECT c.customer_id, c.name, c.segment, t.total_amount, t.txn_count
FROM staging.customer_txn t
JOIN raw.customers c ON t.customer_id = c.customer_id
WHERE t.total_amount > 100;

INSERT INTO mart.high_value_customers
SELECT customer_id, name, total_amount
FROM mart.customer_summary
WHERE total_amount > 10000;
"""

SINGLE_STMT_SQL = """
CREATE TABLE staging.result AS
SELECT id, SUM(val) as total
FROM raw.source
GROUP BY id;
"""


# ---------------------------------------------------------------------------
# compile_sql_string tests
# ---------------------------------------------------------------------------

class TestCompileSqlString:

    def test_returns_string(self):
        result = compile_sql_string(SAMPLE_SQL)
        assert isinstance(result, str)

    def test_output_is_nonempty(self):
        result = compile_sql_string(SAMPLE_SQL)
        assert len(result) > 100

    def test_airflow_imports_present(self):
        result = compile_sql_string(SAMPLE_SQL)
        assert "from airflow import DAG" in result
        assert "from airflow.operators.python import PythonOperator" in result

    def test_dag_id_default(self):
        result = compile_sql_string(SAMPLE_SQL, dag_id="test_dag")
        assert 'dag_id="test_dag"' in result

    def test_dag_owner_injected(self):
        result = compile_sql_string(SAMPLE_SQL, dag_owner="data_team")
        assert '"owner": "data_team"' in result

    def test_schedule_interval_injected(self):
        result = compile_sql_string(SAMPLE_SQL, schedule_interval="0 6 * * *")
        assert 'schedule_interval="0 6 * * *"' in result

    def test_three_tasks_generated(self):
        result = compile_sql_string(SAMPLE_SQL)
        # Count PythonOperator instantiations
        count = result.count("PythonOperator(")
        assert count == 3

    def test_task_ids_in_output(self):
        result = compile_sql_string(SAMPLE_SQL)
        assert "create_customer_txn" in result
        assert "create_customer_summary" in result
        assert "insert_high_value_customers" in result

    def test_dependency_chain_in_output(self):
        result = compile_sql_string(SAMPLE_SQL)
        # Dependency lines must appear
        assert "create_customer_summary.set_upstream(create_customer_txn)" in result
        assert "insert_high_value_customers.set_upstream(create_customer_summary)" in result

    def test_sql_statements_embedded(self):
        result = compile_sql_string(SAMPLE_SQL)
        assert "SQL_STATEMENTS" in result
        assert "raw.transactions" in result
        assert "mart.customer_summary" in result

    def test_tags_included(self):
        result = compile_sql_string(SAMPLE_SQL, tags=["etl", "migration"])
        assert "etl" in result
        assert "migration" in result

    def test_retries_injected(self):
        result = compile_sql_string(SAMPLE_SQL, retries=3)
        assert '"retries": 3' in result

    def test_retry_delay_injected(self):
        result = compile_sql_string(SAMPLE_SQL, retry_delay_minutes=10)
        assert "timedelta(minutes=10)" in result

    def test_single_statement_compiles(self):
        result = compile_sql_string(SINGLE_STMT_SQL, dag_id="single_dag")
        assert "PythonOperator(" in result
        assert "create_result" in result

    def test_single_statement_no_dependency_lines(self):
        result = compile_sql_string(SINGLE_STMT_SQL)
        # No set_upstream calls should appear for single-statement DAG
        assert "set_upstream" not in result

    def test_raises_on_empty_sql(self):
        with pytest.raises(ValueError, match="No SQL statements"):
            compile_sql_string("")

    def test_catchup_false(self):
        result = compile_sql_string(SAMPLE_SQL)
        assert "catchup=False" in result

    def test_auto_generated_header_present(self):
        result = compile_sql_string(SAMPLE_SQL)
        assert "AUTO-GENERATED BY sql-to-dag-compiler" in result

    def test_execute_sql_function_present(self):
        result = compile_sql_string(SAMPLE_SQL)
        assert "def execute_sql(" in result

    def test_output_is_valid_python_syntax(self):
        """Compiled DAG must parse without SyntaxError (compile() checks syntax)."""
        result = compile_sql_string(SAMPLE_SQL)
        try:
            compile(result, "<generated_dag>", "exec")
        except SyntaxError as exc:
            pytest.fail(f"Generated DAG has syntax error: {exc}")


# ---------------------------------------------------------------------------
# compile_sql_file tests
# ---------------------------------------------------------------------------

class TestCompileSqlFile:

    def test_compiles_example_file(self):
        import os
        example_path = os.path.join(
            os.path.dirname(__file__), "..", "examples", "sample_oracle.sql"
        )
        result = compile_sql_file(example_path)
        assert "PythonOperator(" in result

    def test_dag_id_defaults_to_file_stem(self):
        import os
        example_path = os.path.join(
            os.path.dirname(__file__), "..", "examples", "sample_oracle.sql"
        )
        result = compile_sql_file(example_path)
        assert 'dag_id="sample_oracle"' in result

    def test_custom_dag_id_overrides_stem(self, tmp_path):
        sql_file = tmp_path / "my_proc.sql"
        sql_file.write_text(SAMPLE_SQL, encoding="utf-8")
        result = compile_sql_file(str(sql_file), dag_id="custom_dag_id")
        assert 'dag_id="custom_dag_id"' in result

    def test_three_tasks_for_three_statements(self, tmp_path):
        sql_file = tmp_path / "proc.sql"
        sql_file.write_text(SAMPLE_SQL, encoding="utf-8")
        result = compile_sql_file(str(sql_file))
        assert result.count("PythonOperator(") == 3

    def test_raises_on_missing_file(self):
        with pytest.raises(FileNotFoundError):
            compile_sql_file("/nonexistent/file.sql")


# ---------------------------------------------------------------------------
# Dependency correctness integration test
# ---------------------------------------------------------------------------

class TestDependencyCorrectness:

    def test_diamond_dependency_pattern(self):
        """A → B, A → C, B + C → D  (diamond)."""
        diamond_sql = """
        CREATE TABLE staging.a AS SELECT id FROM raw.source;

        CREATE TABLE staging.b AS SELECT id FROM staging.a;

        CREATE TABLE staging.c AS SELECT id FROM staging.a;

        CREATE TABLE mart.d AS
        SELECT b.id FROM staging.b b JOIN staging.c c ON b.id = c.id;
        """
        result = compile_sql_string(diamond_sql, dag_id="diamond")
        # b and c both depend on a
        assert "create_b.set_upstream(create_a)" in result
        assert "create_c.set_upstream(create_a)" in result
        # d depends on b and c
        assert "create_d.set_upstream(create_b)" in result
        assert "create_d.set_upstream(create_c)" in result

    def test_output_dag_has_correct_chain(self):
        """Verify the exact chain for the sample Oracle SQL."""
        import os
        example_path = os.path.join(
            os.path.dirname(__file__), "..", "examples", "sample_oracle.sql"
        )
        result = compile_sql_file(example_path)
        lines = [ln.strip() for ln in result.splitlines()]
        assert "create_customer_summary.set_upstream(create_customer_txn)" in lines
        assert "insert_high_value_customers.set_upstream(create_customer_summary)" in lines
