"""
Example Airflow DAG generated by sql-to-dag-compiler from:

    sql/sales_reporting_pipeline.sql

Compilation timestamp: 2024-01-15T09:23:11Z
Compiler version: sql-to-dag-compiler v1.0.0
Source dialect: PostgreSQL
Target: Apache Airflow 2.8.x

DO NOT EDIT MANUALLY — regenerate with:
    python -m sql_to_dag compile sql/sales_reporting_pipeline.sql \
        --target-dialect airflow \
        --output airflow/dags/compiled_pipeline_example.py
"""
from __future__ import annotations

from datetime import datetime, timedelta

from airflow import DAG
from airflow.providers.postgres.operators.postgres import PostgresOperator
from airflow.providers.postgres.hooks.postgres import PostgresHook
from airflow.operators.python import PythonOperator
from airflow.models import Variable
from airflow.utils.trigger_rule import TriggerRule

# ── Compiler-generated metadata ───────────────────────────────────────────────
PIPELINE_SOURCE_SQL = "sql/sales_reporting_pipeline.sql"
PIPELINE_CHECKSUM = "sha256:a3f1c2d8e9b047..."   # SHA of source SQL file
PIPELINE_TABLES = [
    "raw.orders",
    "raw.customers",
    "raw.products",
    "staging.stg_orders",
    "staging.stg_customers",
    "mart.sales_daily",
    "mart.customer_ltv",
]

POSTGRES_CONN_ID = Variable.get("REPORTING_POSTGRES_CONN_ID", default_var="reporting_db")
SCHEMA_STAGING = Variable.get("STAGING_SCHEMA", default_var="staging")
SCHEMA_MART = Variable.get("MART_SCHEMA", default_var="mart")

DEFAULT_ARGS = {
    "owner": "data-engineering",
    "depends_on_past": False,
    "email_on_failure": True,
    "email_on_retry": False,
    "retries": 2,
    "retry_delay": timedelta(minutes=5),
    "execution_timeout": timedelta(hours=2),
}

# ── Compiled SQL fragments (extracted from source SQL by compiler) ─────────────
# Node: stg_orders
STG_ORDERS_SQL = """
TRUNCATE TABLE {staging}.stg_orders;

INSERT INTO {staging}.stg_orders (
    order_id,
    customer_id,
    order_date,
    status,
    total_amount,
    currency,
    processed_at
)
SELECT
    o.order_id,
    o.customer_id,
    o.order_date::DATE,
    UPPER(TRIM(o.status))          AS status,
    COALESCE(o.total_amount, 0.0)  AS total_amount,
    COALESCE(o.currency, 'USD')    AS currency,
    NOW()                          AS processed_at
FROM raw.orders AS o
WHERE o.order_date >= '{{{{ ds }}}}'::DATE - INTERVAL '7 days'
  AND o.order_id IS NOT NULL;
""".format(staging=SCHEMA_STAGING)

# Node: stg_customers
STG_CUSTOMERS_SQL = """
TRUNCATE TABLE {staging}.stg_customers;

INSERT INTO {staging}.stg_customers (
    customer_id,
    email,
    full_name,
    acquisition_channel,
    signup_date,
    processed_at
)
SELECT
    c.customer_id,
    LOWER(TRIM(c.email))                    AS email,
    TRIM(c.first_name || ' ' || c.last_name) AS full_name,
    COALESCE(c.acquisition_channel, 'unknown') AS acquisition_channel,
    c.signup_date::DATE,
    NOW()                                   AS processed_at
FROM raw.customers AS c
WHERE c.customer_id IS NOT NULL
  AND c.email IS NOT NULL;
""".format(staging=SCHEMA_STAGING)

# Node: sales_daily (depends on: stg_orders, stg_customers)
SALES_DAILY_SQL = """
INSERT INTO {mart}.sales_daily (
    report_date,
    total_orders,
    total_revenue,
    avg_order_value,
    unique_customers,
    new_customers,
    returning_customers
)
SELECT
    so.order_date                                    AS report_date,
    COUNT(DISTINCT so.order_id)                      AS total_orders,
    SUM(so.total_amount)                             AS total_revenue,
    AVG(so.total_amount)                             AS avg_order_value,
    COUNT(DISTINCT so.customer_id)                   AS unique_customers,
    COUNT(DISTINCT CASE
        WHEN sc.signup_date = so.order_date THEN so.customer_id
    END)                                             AS new_customers,
    COUNT(DISTINCT CASE
        WHEN sc.signup_date < so.order_date THEN so.customer_id
    END)                                             AS returning_customers
FROM {staging}.stg_orders AS so
LEFT JOIN {staging}.stg_customers AS sc
    ON so.customer_id = sc.customer_id
WHERE so.order_date = '{{{{ ds }}}}'::DATE
GROUP BY so.order_date
ON CONFLICT (report_date)
DO UPDATE SET
    total_orders        = EXCLUDED.total_orders,
    total_revenue       = EXCLUDED.total_revenue,
    avg_order_value     = EXCLUDED.avg_order_value,
    unique_customers    = EXCLUDED.unique_customers,
    new_customers       = EXCLUDED.new_customers,
    returning_customers = EXCLUDED.returning_customers;
""".format(staging=SCHEMA_STAGING, mart=SCHEMA_MART)

# Node: customer_ltv (depends on: stg_orders, stg_customers)
CUSTOMER_LTV_SQL = """
INSERT INTO {mart}.customer_ltv (
    customer_id,
    email,
    acquisition_channel,
    first_order_date,
    last_order_date,
    total_orders,
    total_revenue,
    avg_order_value,
    days_since_last_order,
    ltv_segment,
    updated_at
)
SELECT
    sc.customer_id,
    sc.email,
    sc.acquisition_channel,
    MIN(so.order_date)                AS first_order_date,
    MAX(so.order_date)                AS last_order_date,
    COUNT(DISTINCT so.order_id)       AS total_orders,
    SUM(so.total_amount)              AS total_revenue,
    AVG(so.total_amount)              AS avg_order_value,
    CURRENT_DATE - MAX(so.order_date) AS days_since_last_order,
    CASE
        WHEN SUM(so.total_amount) >= 10000 THEN 'platinum'
        WHEN SUM(so.total_amount) >= 5000  THEN 'gold'
        WHEN SUM(so.total_amount) >= 1000  THEN 'silver'
        ELSE 'bronze'
    END                               AS ltv_segment,
    NOW()                             AS updated_at
FROM {staging}.stg_customers AS sc
JOIN {staging}.stg_orders AS so
    ON sc.customer_id = so.customer_id
   AND so.status NOT IN ('cancelled', 'refunded')
GROUP BY sc.customer_id, sc.email, sc.acquisition_channel
ON CONFLICT (customer_id)
DO UPDATE SET
    last_order_date       = EXCLUDED.last_order_date,
    total_orders          = EXCLUDED.total_orders,
    total_revenue         = EXCLUDED.total_revenue,
    avg_order_value       = EXCLUDED.avg_order_value,
    days_since_last_order = EXCLUDED.days_since_last_order,
    ltv_segment           = EXCLUDED.ltv_segment,
    updated_at            = EXCLUDED.updated_at;
""".format(staging=SCHEMA_STAGING, mart=SCHEMA_MART)


def _validate_row_counts(**context) -> None:
    """
    Post-load validation: assert staging tables have rows.
    Fails the task if counts are unexpectedly zero.
    """
    hook = PostgresHook(postgres_conn_id=POSTGRES_CONN_ID)
    checks = {
        f"{SCHEMA_STAGING}.stg_orders": "SELECT COUNT(*) FROM staging.stg_orders",
        f"{SCHEMA_STAGING}.stg_customers": "SELECT COUNT(*) FROM staging.stg_customers",
    }
    for table, sql in checks.items():
        count = hook.get_first(sql)[0]
        if count == 0:
            raise ValueError(f"Row count validation FAILED for {table}: got 0 rows")
        context["task_instance"].xcom_push(key=f"row_count_{table}", value=count)


with DAG(
    dag_id="compiled_sales_reporting_pipeline",
    default_args=DEFAULT_ARGS,
    description=(
        f"Auto-generated by sql-to-dag-compiler from {PIPELINE_SOURCE_SQL}. "
        "Stages orders/customers → materializes daily sales + LTV mart tables."
    ),
    schedule_interval="@daily",
    start_date=datetime(2024, 1, 1),
    catchup=False,
    max_active_runs=1,
    tags=["generated", "sales", "reporting", "postgresql"],
    doc_md=__doc__,
) as dag:

    # ── Stage: raw → staging ──────────────────────────────────────────────────
    stage_orders = PostgresOperator(
        task_id="stage_orders",
        postgres_conn_id=POSTGRES_CONN_ID,
        sql=STG_ORDERS_SQL,
    )

    stage_customers = PostgresOperator(
        task_id="stage_customers",
        postgres_conn_id=POSTGRES_CONN_ID,
        sql=STG_CUSTOMERS_SQL,
    )

    # ── Validate staging data quality ─────────────────────────────────────────
    validate_staging = PythonOperator(
        task_id="validate_staging",
        python_callable=_validate_row_counts,
        provide_context=True,
    )

    # ── Mart: staging → mart (can run in parallel) ────────────────────────────
    load_sales_daily = PostgresOperator(
        task_id="load_sales_daily",
        postgres_conn_id=POSTGRES_CONN_ID,
        sql=SALES_DAILY_SQL,
    )

    load_customer_ltv = PostgresOperator(
        task_id="load_customer_ltv",
        postgres_conn_id=POSTGRES_CONN_ID,
        sql=CUSTOMER_LTV_SQL,
    )

    # ── Completion marker ─────────────────────────────────────────────────────
    @dag.task(task_id="mark_complete", trigger_rule=TriggerRule.ALL_SUCCESS)
    def mark_complete(**context):
        ds = context["ds"]
        ti = context["task_instance"]
        stg_order_count = ti.xcom_pull(
            task_ids="validate_staging",
            key=f"row_count_{SCHEMA_STAGING}.stg_orders",
        )
        print(f"Pipeline complete for {ds}. Staged {stg_order_count} orders.")

    # ── Dependency graph (compiler-derived from SQL lineage) ──────────────────
    [stage_orders, stage_customers] >> validate_staging
    validate_staging >> [load_sales_daily, load_customer_ltv]
    [load_sales_daily, load_customer_ltv] >> mark_complete()
