# ============================================================
# AUTO-GENERATED BY sql-to-dag-compiler
# Source: sample_oracle.sql
# Generated: 2026-05-30 05:09:50 UTC
# DO NOT EDIT — re-run the compiler to regenerate.
# ============================================================

from datetime import datetime, timedelta

from airflow import DAG
from airflow.operators.python import PythonOperator

# ---------------------------------------------------------------------------
# Default arguments applied to every task
# ---------------------------------------------------------------------------
default_args = {
    "owner": "airflow",
    "depends_on_past": False,
    "email_on_failure": False,
    "email_on_retry": False,
    "retries": 1,
    "retry_delay": timedelta(minutes=5),
}

# ---------------------------------------------------------------------------
# SQL statements — keyed by task id
# ---------------------------------------------------------------------------
SQL_STATEMENTS = {
    "create_customer_txn": """
    -- ============================================================
    -- procedure: load_customer_summary
    -- Source: Oracle Data Warehouse → AWS Redshift migration
    -- Originally a PL/SQL stored procedure in a prior enterprise data-engineering project (2021-2022)
    -- ============================================================

    -- Step 1: Build staging aggregate from raw transaction data
    CREATE TABLE staging.customer_txn AS
    SELECT customer_id, SUM(amount) as total_amount, COUNT(*) as txn_count
    FROM raw.transactions
    WHERE txn_date >= TRUNC(SYSDATE) - 30
    GROUP BY customer_id;
""",
    "create_customer_summary": """
    -- Step 2: Enrich with customer dimension data
    CREATE TABLE mart.customer_summary AS
    SELECT c.customer_id, c.name, c.segment, t.total_amount, t.txn_count
    FROM staging.customer_txn t
    JOIN raw.customers c ON t.customer_id = c.customer_id
    WHERE t.total_amount > 100;
""",
    "insert_high_value_customers": """
    -- Step 3: Populate high-value customer segment
    INSERT INTO mart.high_value_customers
    SELECT customer_id, name, total_amount
    FROM mart.customer_summary
    WHERE total_amount > 10000;
""",
}


def execute_sql(task_id: str, **context) -> None:
    """
    Execute the SQL statement for *task_id*.

    In production, replace this stub with your Redshift/PostgreSQL hook:

        from airflow.providers.amazon.aws.hooks.redshift_sql import RedshiftSQLHook
        hook = RedshiftSQLHook(redshift_conn_id="redshift_default")
        hook.run(SQL_STATEMENTS[task_id])
    """
    sql = SQL_STATEMENTS[task_id]
    print(f"[{task_id}] Executing SQL ({len(sql)} chars):")
    print(sql[:200] + ("..." if len(sql) > 200 else ""))
    # TODO: wire to RedshiftSQLHook / PostgresHook


# ---------------------------------------------------------------------------
# DAG definition
# ---------------------------------------------------------------------------
with DAG(
    dag_id="sample_oracle",
    default_args=default_args,
    description="Auto-generated from sample_oracle.sql",
    schedule_interval="@daily",
    start_date=datetime(2026, 5, 1),
    catchup=False,
    tags=["sql-to-dag", "generated"],
) as dag:
    create_customer_txn = PythonOperator(
        task_id="create_customer_txn",
        python_callable=execute_sql,
        op_kwargs={"task_id": "create_customer_txn"},
        doc_md="""
**Statement type:** CTAS
**Target table:** staging.customer_txn
**Source tables:** raw.transactions
**Aggregations:** COUNT, SUM
**Has WHERE clause:** True
**Has GROUP BY:** True
        """,
    )
    create_customer_summary = PythonOperator(
        task_id="create_customer_summary",
        python_callable=execute_sql,
        op_kwargs={"task_id": "create_customer_summary"},
        doc_md="""
**Statement type:** CTAS
**Target table:** mart.customer_summary
**Source tables:** staging.customer_txn, raw.customers
**Aggregations:** none
**Has WHERE clause:** True
**Has GROUP BY:** False
        """,
    )
    insert_high_value_customers = PythonOperator(
        task_id="insert_high_value_customers",
        python_callable=execute_sql,
        op_kwargs={"task_id": "insert_high_value_customers"},
        doc_md="""
**Statement type:** INSERT_SELECT
**Target table:** mart.high_value_customers
**Source tables:** mart.customer_summary
**Aggregations:** none
**Has WHERE clause:** True
**Has GROUP BY:** False
        """,
    )

    # ---------------------------------------------------------------------------
    # Task dependencies (derived from table-level lineage)
    # ---------------------------------------------------------------------------
    create_customer_summary.set_upstream(create_customer_txn)
    insert_high_value_customers.set_upstream(create_customer_summary)
